target: genrl.policies.low.dt.nn.DecisionTransformer

cfg:
  observation_dim: ${env.observation_dim}
  action_dim: ${env.action_dim}
  subseq_len: ${subseq_len}

  optimizer_class: adam
  lr: 1e-4
  optimizer_kwargs: {}

  policy:
    gpt2_config:
      vocab_size: 1
      n_positions: 1024
      n_layer: 4
      n_head: 16
      activation_function: relu
      resid_pdrop: 0.1
      embd_pdrop: 0.1
      attn_pdrop: 0.1
      layer_norm_epsilon: 0

    embed_dim: 64
    hidden_dim: 64
    output_dim: ${env.action_dim}
    dropout: ${dropout}
    activation_fn: relu
    act_scale: 1.20
    max_ep_len: 1024