target: genrl.policies.low.MLPBCAgent


defaults:
  - mlp/policy: mlp

kwargs:
  seed: ${seed}
  cfg:
    observation_dim: ${env.observation_dim}
    action_dim: ${env.action_dim}

    policy: ${low_policy.mlp.policy}
